SELECT * FROM jaeger;
SELECT * FROM jaeger WHERE status = 'Destroyed';
SELECT * FROM jaeger WHERE mark IN ('Mark-2', 'Mark-4');
SELECT * FROM jaeger WHERE mark NOT IN ('Mark-2', 'Mark-4');
SELECT modelName FROM jaeger ORDER BY mark;
SELECT modelName FROM jaeger WHERE height >= '80';
SELECT MAX(kaijuKill) FROM jaeger;
SELECT AVG(weight) FROM jaeger;
UPDATE jaeger SET kaijuKill = kaijuKill + 1 WHERE status = 'Not destroyed';
DELETE FROM jaeger WHERE status = 'Destroyed';
SELECT * FROM jaeger;
